# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "🛠 Build an IPA for Ad Hoc distribution"
  lane :build_ipa do
    build_ios_app(
      workspace: "KrachisSpaceApp.xcworkspace",
      scheme: "SpaceApp",
      export_method: "development",
      output_directory: "../build/ios",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "development",
        signingStyle: "automatic",
        teamID: "P65AA242M9"
      }
    )
  end
end
