name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths: 
      - 'src/frontend/mobile/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python (for EB CLI)
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install EB CLI
      run: pip install awsebcli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init ${{ secrets.EB_APP_NAME }} --region ${{ secrets.AWS_REGION }} --platform "node.js-22"
        eb use ${{ secrets.EB_ENV_NAME }}
        eb deploy --staged --timeout 20
